version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pass@123"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - sql_data:/var/opt/mssql

  library-app:
    build: .
    container_name: library-app
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver
    restart: always

volumes:
  sql_data:
